db.system.js.save({_id:"fnLoadUserNotification",value:function(i){return db.clnNotification.findOne({userRoleMappingId:ObjectId(i)},{notification:1})}});

db.system.js.save({_id:"fnSaveUserFeedback",value:function(e,s,n){var o=db.clnFeedbacks.findOne({_id:ObjectId(e)});void 0==o.userResponse&&(o.userResponse=[]),s.userResponse.rmId=ObjectId(s.userResponse.rmId),o.userResponse.push(s.userResponse);for(var t=0;t<o.questions.length;t++){var r=o.questions[t].data;for(optionsCount=1;optionsCount<r.length;optionsCount++)-1!=s.responseObject[t].indexOf(r[optionsCount][0])&&(r[optionsCount][1]=r[optionsCount][1]+1)}return o.responseCount=o.responseCount+1,o.updatedDate=ISODate(),db.clnFeedbacks.save(o),fnArchiveUserNotification(n,e,n)}});

db.system.js.save({_id:"fnLoadFeedbackRequestDetails",value:function(e,d,s){var n=db.clnFeedbacks.findOne({_id:ObjectId(d),companyId:ObjectId(e),userResponse:{$elemMatch:{rmId:ObjectId(s)}}},{title:1,description:1,type:1,feedbackTypeId:1,questions:1,userResponse:1});return null==n&&(n=db.clnFeedbacks.findOne({_id:ObjectId(d),companyId:ObjectId(e)},{userResponse:0})),n}});

db.system.js.save({_id:"fnViewFeedbackRequests",value:function(e,t){var d={},a=db.clnFeedbacks.find({targetList:{$in:[ObjectId(e)]},companyId:ObjectId(t),userResponse:{$not:{$elemMatch:{rmId:ObjectId(e)}}},validUntil:{$gt:ISODate()}},{title:1,description:1,createdDate:1}).sort({createdDate:-1}).toArray(),c=db.clnFeedbacks.find({targetList:{$in:[ObjectId(e)]},companyId:ObjectId(t),userResponse:{$elemMatch:{rmId:ObjectId(e)}}},{title:1,description:1,createdDate:1}).sort({createdDate:-1}).toArray();return d.pendingFeedback=a,d.submitedFeedback=c,d}});

db.system.js.save({_id:"fnArchiveUserNotification",value:function(i,t,e){var n=db.clnNotification.findOne({userRoleMappingId:ObjectId(i)},{notification:{$elemMatch:{typeId:ObjectId(t)}},_id:0});n.notification[0].archivedDate=ISODate(),n.createdDate=ISODate(),n.updatedDate=ISODate(),n.crmId=e,n.urmId=e,n.activeFlag=1,n.userRoleMappingId=ObjectId(i);var a="";a=db.clnArchiveNotification.findOne({userRoleMappingId:ObjectId(i)}),null==a?db.clnNotification.insert(n):db.clnArchiveNotification.update({userRoleMappingId:ObjectId(i)},{$push:{notification:userNotifiction.notification[0]}});db.clnNotification.update({userRoleMappingId:ObjectId(i)},{$pull:{notification:{typeId:ObjectId(t)}}},{multi:!0});return fnLoadUserNotification(i)}});

db.system.js.save({_id:"fnLoadUsersUnderRole",value:function(e,r){"string"==typeof e&&(e=ObjectId(e));var a=db.clnUserRoleMapping.find({fkRoleId:e,profile:{$elemMatch:{fkCompanyId:ObjectId(r)}},activeFlag:1},{fkUserLoginId:1}).toArray(),d=[];return a.forEach(function(e){userData={},userData.roleMappingId=ObjectId(e._id.valueOf());var r=db.clnUserDetails.find({fkUserLoginId:ObjectId(e.fkUserLoginId.valueOf())},{profile:1,_id:0}).toArray();userData.profile=r[0].profile,d.push(userData)}),d}});

db.system.js.save({_id:"fnInsertNotificationDetails",value:function(e,i,t,a,n){var o={};o.userRoleMappingId="",o.notification=[{type:t,typeId:i,date:ISODate(),message:a}],o.createdDate=ISODate(),o.updatedDate=ISODate(),o.crmId=n,o.urmId=n,o.activeFlag=1;var d="";if(null!=e.length)for(var l=0;l<e.length;l++)o.userRoleMappingId=e[l],d=db.clnNotification.findOne({userRoleMappingId:o.userRoleMappingId}),null==d?db.clnNotification.insert(o):db.clnNotification.update({userRoleMappingId:o.userRoleMappingId},{$push:{notification:o.notification[0]}});return o}});

db.system.js.save({_id:"fnSaveFeedbackForm",value:function(e){e.validUntil=ISODate(e.validUntil),e.createdDate=ISODate(),e.updatedDate=ISODate(),e.crmId=ObjectId(e.rmId),e.urmId=ObjectId(e.rmId),delete e.rmId,e.companyId=ObjectId(e.companyId),e.targetList=[];var t=e.feedbackAbout;delete e.feedbackAbout;for(var a=0;a<t.feedbackOn.length;a++)if(e.feedbackTypeId=ObjectId(t.feedbackOn[a]),"Public"==e.formAccessTo&&(e.targetList=db.clnUserRoleMapping.distinct("_id",{fkCompanyId:e.companyId,activeFlag:1})),"course"==t.type&&(e.targetList=e.targetList.concat(db.clnUserCourseMapping.distinct("fkUserRoleMappingId",{fkCompanyId:e.companyId,fkCourseId:e.feedbackTypeId}))),e.targetList.length){e._id=new ObjectId,e.type=t.type;for(var d=e.targetList.sort(),i=0;e.targetList.length-1>i;i++)e.targetList[i].valueOf()==e.targetList[i+1].valueOf()&&d.splice(i,1);return e.targetList=d,db.clnFeedbacks.insert(e),fnInsertNotificationDetails(e.targetList,e._id,"feedback",e.title,e.crmId)}return{temp:d.length,list:e.targetList.length}}});
